_VermilionGymLTSurgePreBattleText::
text "Hé, gamin!"
line "Tu fais quoi là?"
para "Tu ne résisterais"
line "pas longtemps"
cont "en temps de"
cont "guerre!"
para "Je vais te dire,"
line "mes #MON"
cont "électriques m'ont"
cont "sauvé la vie!"
cont "Et ouais!"
para "Ils ont paralysé"
line "mes ennemis avec"
cont "leurs éclairs!"
cont "Une vraie"
cont "boucherie!"
para "Y va t'arriver la"
line "même chose!"
cont "Compte tes dents!"
cont "Tu vas morfler!"
done

_VermilionGymGarbageNearSurgeText::
	text "An empty can is"
	line "in the trash."
	para "ARMY FIELD RATION"
	line "CHEDDAR CHEESE"
	cont "is written on it."
	done

_VermilionGymBookshelfText::
	text "A bunch of books"
	line "on military"
	cont "topics."
	para "A HISTORY OF"
	line "SERVICE #MON,"
	para "RECONNAISSANCE"
	line "SPEAROW STYLE,"
	para "THE DANGER OF"
	line "DITTO SPIES<...>"